# -*- coding: utf-8 -*-
"""YouTube trend analyser

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fzz7wrFVhqF2eB3WkRpzIw7Q3YgWC9u0
"""

import pandas as pd
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
import seaborn as sns

"""CSV FILE READ"""

df = pd.read_csv('INvideos.csv')

df.head()

df.describe()

df.info()

df[df["description"].apply(lambda x: pd.isna(x))].head(3)

df["description"] = df["description"].fillna(value="")

"""DATASET COLLECTION YEAR

"""

cdf = df["trending_date"].apply(lambda x: '20' + x[:2]).value_counts().reset_index()

cdf.columns = ["year", "No_of_videos"]

plt.figure()
plt.bar(cdf["year"], cdf["No_of_videos"])

plt.xlabel("Year")
plt.ylabel("No. of Videos")
plt.title("Number of Trending Videos per Year")

plt.show()

"""HISTOGRAM BETWEEN 10 AND 20 MILLION VIEWS
AND HOW MANY VIDEO BETWEEN 20 AND 30 MILLION


"""

plt.figure()
plt.hist(df["views"], bins=50)

plt.xlabel("Views")
plt.ylabel("Number of Videos")
plt.title("Distribution of Views")

plt.show()

plt.figure()

plt.hist(df[df["views"] < 25e6]["views"], bins=50)

plt.xlabel("Views")
plt.ylabel("No. of Videos")
plt.title("Views Distribution (Below 25M)")

plt.show()

df[df['views'] < 1e6]['views'].count() / df['views'].count() * 100

df[df['views'] < 1.5e6]['views'].count() / df['views'].count() * 100

df[df['views'] < 5e6]['views'].count() / df['views'].count() * 100

"""LIKES HISTOGRAM"""

plt.figure()

plt.hist(df["likes"], bins=50)

plt.xlabel("Likes")
plt.ylabel("No. of Videos")
plt.title("Likes Distribution")
plt.title("Distribution of Likes ")
plt.show()

filtered_likes = df[df["likes"] <= 1e5]["likes"]

plt.figure()
plt.hist(filtered_likes, bins=50)

plt.xlabel("Likes")
plt.ylabel("No. of Videos")
plt.title("Distribution of Likes (Less than 100,000)")

plt.show()

"""PERCENTAGE OF TRENDING VIDEO LESS THAN 40,000 LIKES

"""

df[df['likes'] < 4e4]['likes'].count() / df['likes'].count() * 100

"""PERCENTAGE OF VIDEO WITH LESS THAN 100,000 likes"""

df[df['likes'] < 10e4]['likes'].count() / df['likes'].count() * 100

filtered_comments = df[df["comment_count"] < 100000]["comment_count"]

plt.figure()
plt.hist(filtered_comments, bins=50)

plt.xlabel("Comment Count")
plt.ylabel("No. of Videos")
plt.title("Distribution of Comment Count (Less than 100,000)")

plt.show()

filtered_comments = df[df["comment_count"] < 200000]["comment_count"]

plt.figure()
plt.hist(filtered_comments, bins=50)

plt.xlabel("Comment Count")
plt.ylabel("No. of Videos")
plt.title("Distribution of Comment Count (Less than 200,000)")

plt.show()

"""PERCENTAGE OF VIDEO WITH LESS THAN 3500 COMMENTS

"""

df[df['comment_count'] < 3500]['comment_count'].count() / df['comment_count'].count() * 100

"""PERCENTAGE OF VIDEO WITH LESS THAN 25000 COMMENTS"""

df[df['comment_count'] < 25000]['comment_count'].count() / df['comment_count'].count() * 100

"""VIDEO TITLE LENGTHS"""

df["title_length"] = df["title"].apply(lambda x: len(x))
df.head()

"""HISTOGRAM OF TITLE LENGTHS"""

plt.figure()
plt.hist(df["title_length"], bins=30)

plt.xlabel("Title Length")
plt.ylabel("No. of Videos")
plt.title("Distribution of Video Title Length")

plt.show()

"""SCATTER PLOT TO STUDY RELATIONSHIP BETWEEN TITLE LENGTH AND NO OF VIEWS

"""

plt.figure()

plt.scatter(df["views"], df["title_length"])

plt.xlabel("Views")
plt.ylabel("Title Length")
plt.title("Views vs Title Length")

plt.show()

"""CORRELATION BETWEEEN DATASET VARIABLES"""

df.corr(numeric_only=True)

import seaborn as sns
import matplotlib.pyplot as plt
numeric_df = df.select_dtypes(include=['number'])

plt.figure()
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")

plt.title("Correlation Heatmap of Numerical Features")
plt.show()

"""The correlation map and correlation table above say that views and likes are highly positively correlated.

Which Channels have largest number of trending videos?
"""

cdf = df.groupby("channel_title").size().reset_index(name="video_count")
cdf = cdf.sort_values("video_count", ascending=False).head(20)

plt.figure()

plt.barh(cdf["channel_title"], cdf["video_count"])

plt.xlabel("No. of Videos")
plt.ylabel("Channel")
plt.title("Top 20 Channels by Number of Trending Videos")



plt.show()

"""Which video category has the largest number of trending videos?"""

import json

with open("IN_category_id.json") as file:
    data = json.load(file)

cat_dict = {int(item["id"]): item["snippet"]["title"] for item in data["items"]}

df["category_name"] = df["category_id"].map(cat_dict)

df.head()

cdf = df["category_name"].value_counts().reset_index()
cdf.columns = ["category_name", "No_of_videos"]

plt.figure()

plt.bar(cdf["category_name"], cdf["No_of_videos"])

plt.xlabel("Category")
plt.ylabel("No. of Videos")
plt.title("Number of Videos by Category")

plt.xticks(rotation=90)

plt.show()

print("Entertainment:", len(df[df["category_name"] == "Entertainment"]))
print("News & Politics:", len(df[df["category_name"] == "News & Politics"]))
print("Music:", len(df[df["category_name"] == "Music"]))
print("Movies:", len(df[df["category_name"] == "Movies"]))
print("Travel & Events:", len(df[df["category_name"] == "Travel & Events"]))
print("Pets & Animals:", len(df[df["category_name"] == "Pets & Animals"]))

df["publish_time"] = pd.to_datetime(df["publish_time"])

df["publishing_day"] = df["publish_time"].dt.day_name()
df["publishing_hour"] = df["publish_time"].dt.hour

cdf = df["publishing_day"].value_counts().reset_index()
cdf.columns = ["publishing_day", "No_of_videos"]

plt.figure()

plt.bar(cdf["publishing_day"], cdf["No_of_videos"])

plt.xlabel("Publishing Day")
plt.ylabel("No. of Videos")
plt.title("Number of Videos by Publishing Day")

plt.xticks(rotation=45)

plt.show()

cdf = df["publishing_hour"].value_counts().sort_index()

plt.figure()

plt.bar(cdf.index, cdf.values)

plt.xlabel("Publishing Hour")
plt.ylabel("No. of Videos")
plt.title("Number of Videos by Publishing Hour")

plt.show()

"""Conclusions

We analyzed a dataset that contains information about YouTube trending videos for 205 days. The dataset was collected in 2017 and 2018 and contains 37352 video entries.

86% of trending videos have less than 1.5 million views, and 95% have less than 5 million views.

87% of trending videos have less than 40,000 likes, and 94% have less than 100,000 likes.

88% of trending videos have less than 3,500 comments, and 97% have less than 25,000 comments.

There is a strong positive correlation between the number of views and the number of likes of trending videos: As one of them increases, the other increases, and vice versa.

There is a strong positive correlation also between the number of likes and the number of comments, and a slightly weaker one between the number of dislikes and the number of comments.

The category that has the largest number of trending videos is 'Entertainment' with 16,712 videos, followed by 'News & Politics' category with 5241 videos, followed by 'Music' category with 3858 videos.

On the opposite side, the category that has the smallest number of trending videos is 'Pets & Animals' with 3 videos, followed by 'Travel & Events' with 8 videos, followed by 'Movies' with 16 videos.


"""